--	File: create_schema1.sql
--	Author:	Donald Raikes
--	Date Created:  2021-02-02

-- drop objects
drop table product_categories cascade constraints;
drop table products cascade constraints;

-- create tables
create table product_categories (
    product_category_id            number generated by default on null as identity 
                                   constraint product_categories_id_pk primary key,
    category                       varchar2(20 char)
                                   constraint product_categories_categor_unq unique not null,
    short_desc                     varchar2(255 char) not null,
    image_path                     varchar2(200 char)
)
;

create table products (
    product_id                     number generated by default on null as identity 
                                   constraint products_id_pk primary key,
    product_category_id            number
                                   constraint products_product_category_i_fk
                                   references product_categories on delete cascade,
    name varchar2(100 char)
                                   constraint products_product_name_unq unique not null,
    short_desc                     varchar2(400 char) not null,
    price                     number(10,2),
    quantity                       number,
	quantity_shipped number,
	quantity_instock  number,
    image                     varchar2(200 char) not null
)
;

-- table index
create index products_i1 on products (product_category_id);

-- load data
 
-- Generated by Quick SQL Tuesday February 02, 2021  16:59:40
 
/*
product_categories
	category  vc20 /nn /unique
	short_desc  vc255 /nn
	image_path  vc200
	products
		product_name  vc100 /nn /unique
		short_desc  vc400 /nn
		quantity  number
		unit_price  number
		image_path  vc200 /nn

# settings = { PK: "IDENTITY", semantics: "CHAR", DB: "18c", drop: true, longVC: true, language: "EN", APEX: true, prefixPKwithTname: true }
*/
